name: pytest on Unix OS

on:
  pull_request:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

env:
  source_dir: omf

jobs:
  pytest:
    name: pytest (Unix)
    strategy:
      fail-fast: false
      matrix:
        python_ver: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      POETRY_VIRTUALENVS_CREATE: true
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_ver }}
      - name: Get full Python version
        id: full-python-version
        run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/.poetry python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        env:
          # Increase this value to reset cache if poetry.lock has not changed
          CACHE_NUMBER: 1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}-{{ env.CACHE_NUMBER }}
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: timeout 10s poetry run pip --version || rm -rf .venv
      - name: Install dependencies
        run: poetry install -vvv
      - name: pytest
        run: poetry run pytest --cov-report=xml --cov=${source_dir} --cov-branch --cov-fail-under=79
